{% set version = "1.2.2" %}

package:
  name: osmapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/osmapi/osmapi-{{ version }}.tar.gz
  sha256: f80749c3bf414138c82790da2179519b63d60ce7146d471ba6c651307f5b77f1

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - requests
  run:
    - python
    - requests

test:
  imports:
    - osmapi

about:
  home: https://github.com/metaodi/osmapi
  license: GPL 3.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Python wrapper for the OSM API'

extra:
  recipe-maintainers:
    - ocefpaf
