travis:
  secure:
    BINSTAR_TOKEN: WB/dhRRUYL+WdE/WQ7yLZThZVb+232CK2RtRmWcLML8D+4VqwSoRjAr+yX8GqHzW+Hbt3uy9oDGfXFONnSrimxm+3eZZ74tn6+PQyur3Q8akDQY9N8caCj0GgL/JsOGdgurMXf91vZPWkPZ7lrKbW6iQNNAaWpNJO4kV3C8G/IkuI8HeickhDKS7XAPWOUmJ/TnQcK635nanHvPkyR6J4R3DvraBgpq/GhHTnhPkxQhLqCY/zHkWq91q3s4fv+8UiLPlxkOxt4XFl5Ajh6CkLKAgsxtcxbFEKtYEoX+18gd62s2kU3XUnPAzmJWQdaXwgONmhGPdnzS1Os17vEGpUlMiA1cM1NkRlrdn8VuYEibxNPcLRWrTYlDO5d58mEBAwIck6bLucorewpFVmx9G7v2e5vTeZnFBcfYQTCZuIFtt2lpPLRrO1cRlaXRZCgAmr/xZ/KUh7N0t7O7f5zEqL8V3sNNiZsrt5HoVFqKfinY1y/ksKuZ1S+pAHnPX8AjL8tSR24ah4QixbjXy9IhdE0tYdv1edLh0CgU7RRJSkPp30Xxbt3Iv4D/j8yW3+uM3cDL66VWPv27rt79Zv2ZV5lR7jY06a4+ReR55yjYsZXVJCH4O4Eyt+MMHBauSvaIjQAQAtAGg+RDK20Tl/G6tcsuRHEQy8A5PIj6sTd80oh4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
