travis:
  secure:
    BINSTAR_TOKEN: 32aHNOjNrJoQp82WAC8Ov5NPXLQBGzH04+XYmbSBUeeAIh4KHFAjuSxfFbWTVSXfwnlSaThXOgA4X0Ky1sC7550KiQiScNrSRhTbEEbPor1nKiSSfUf1vtru4waD9Fpj24EgOWUMM9YcVod04eTVKu60eWK4LQ21VrWtOiWV1HMsOcTyjDSy3fDZu2xGsmqxS98mtaAlZVdn9rh8VqBf3IQTbQ5LXv1QMOnwMTIQ/s5W6ljKs1I/S/7LrMCQz5GruDlKPfErNRhU6TC5TgGabE0niJA+7zwAdTAHdXakOuj80DCr6rrIpL85NhtNHqxGM/xMKccrKvBbU//dB6H8LuCLDKsCa7+bL0I+8B6FHzRnGqCX/EFn8O2YP9TxRWy95vs6i2M2bj/tLoIH3xKSmNvirVBXSmcMvFVDKAstq9AocMsXza3pFzKr3BhNJUmWAzycxg2KJ5eD6QSj9AJGLAMb30Un+gL3LCrMllEUGCMA9O+/ouBp7kzK7kVl3aYYzNk/umff7zpvc6avMUqlaVFzo0ea9va3v5GLeo+6vncgstLHwEiLDdVRxWXQuWppa6c7zwMqQ6ENDKuBDsfJuP/A7Fl6AuMrlOWIhYGigQYhq8rtAsuq/6+kyjhimfm/fpg0a0bckHIcxzosLcnNtk1LqGpzQYun/OdUKjn9pN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
